# Configuration

## Mandatory files

The project has the following mandatory files:

1. *<name-of-project>.Rproj*,

2. *\_bookdown.yml*,

3. *\_output.yml*,

4. *.git*,

5. *.gitignore*,

6. *README.md*,

7. *book.bib*,

8. *default.latex*,

9. *index.Rmd*,

10. *js.html*,

11. *js.js*,

12. *preamble.tex*,

13. *references.Rmd*, and

14. *style.css*.

i explain the purpose and content of each file.

## *<name-of-project>.Rproj*

This is the project metadata file for RStudio Server.

## *\_bookdown.yml*

This file is used because in *index.Rmd*, the value for `site` is `bookdown::bookdown_site`.

Inside the file *\_bookdown.yml*, the following settings are:

```
book_filename: "<name-of-project>"
```

This was set already in the  [setup phase](#book-filename). Once i give RStudio Server the command *Build Book* it creates the output Portable Document Format (PDF) file with the given name for `book_filename` by adding the file extension *.pdf* inside the subfolder *\_book*.

```
new_session: false
```

For multi-chaptered or -sectioned outputs, every chapter or section is meant to be in a separate R markdown (Rmd) file. In order to be reference parts from one Rmd file to another Rmd file, the value for `new_session` must be `false`. Otherwise, a new session will be created for every file and referencing between the files isn't possible.

```
delete_merged_file: true
```

During building, all the included Rmd files will be merged into one Rmd file that will be used for generating \TeX file. That merged Rmd file is usually unnecessary, so i let RStudio Server delete it automatically.

```
rmd_files: [
  "index.Rmd",
  <<rmd/...,>>
  "references.Rmd"
]
```

`rmd_files` contains the list of involved Rmd files. There must be involved *index.Rmd* as only that file can have `site` which is necessary for generating anything at all. *references.Rmd* contains references and usually, i have references, so i include the file. If `rmd_files` isn't present then all the files whose name doesn't start by *\_* will be included sorted according to their names. With `rmd_files`, i can also set the order of files.

## *\_output.yml*

### Introduction

This file is used because in *index.Rmd*, the value for `site` is `bookdown::bookdown_site`.

Inside the file *\_output.yml*, the output types can be set. i only use two of them: a web format `bs4_book` and a print format `pdf_book`.

### `bookdown::bs4_book`

The following settings are for `bookdown::bs4_book`:

```
css: style.css
```

In *style.css*, it's possible to restyle the website.

```
  includes:
    in_header: js.html
```

i don't like if i lead the user from my site away once they click a link to an external site on my bibliography page. Therefore, i wrote a program in ECMAScript that adds `target = "_blank"` to every `a` in the bibliography after the whole page is loaded. i put the script into the file *js.js* as i want to keep scripts written in different languages in separate files. Then, i created the file *js.html* that reads the content of *js.js*. i want the script tag to be put into `head` - therefore `in_header`.

```
repo: https://github.com/<username-in-github>/<name-of-project>
```

The repository will be linked in three places. In the left column, there's the link for the main page of the repository. In the right column, there are two links regarding to the repo. The upper one refers the repo page of the current page and the lower link leads to the repo page where the current page can be edited. In GitHub, discussions can take place.

### `bookdown::pdf_book`

The following settings are for `bookdown::pdf_book`:

[]{#preamble}
```
  includes:
    in_header: preamble.tex
```

As the default \LaTeX template file is *default.tex*, i don't want to change that and instead, offer additions and modifications through `includes`. In the file whose name is given - *preamble.tex*, the additions and modifications can be made.

```
  keep_tex: yes
```

As PDF-file is generated according to \TeX file, it's sometimes useful to see what \TeX file consists of.

```
  template: default.latex
```

In order to make everything work, it's useful to use the default template downloaded from *pandoc*'s repository [@macfarlane_2022_pandoc]. Modifications can be done in [*preamble.tex*](#preamble) or as `extra_dependencies`. i never edit *default.latex*.

```
  extra_dependencies:
    <name-of-package>: <option-for-package>
    ...
```

As i don't change *default.latex*, if i need to include a package that isn't included there, i can do it in `extra_dependencies` where i can list the packages by name following by a colon following by package options. If i set no options then i set `null` as the option.

## *.git*

This folder is for *git* configuration regarding to this project.

## *.gitignore*

This file contains the list of files *git* should ignore.

## *README.md*

This file contains the human-friendly metainformation about the project.

## [*book.bib*](#book_bib)

This is the bibliography file.

## *default.latex*

This is the default \LaTeX template downloaded from @macfarlane_2022_pandoc.

## *index.Rmd*

This file must contain the site generator information in the metadata section and can contain other metadata there. In addition, it serves as the holder of common functions and commands and contains an introduction as if the number of Rmd files and first-level headings don't match, a warning will be given.

The optional metadata can be the following:

```
author: "<the name of the author>"
```

```
colorlinks: TRUE
```

i want that the user sees what part of the text is a link.

```
date: "`r Sys.Date()`" # the current date or any other date if set otherwise
description: "<description of the project>"
lang: <two-letter lowercase language code>
title: "<the title of the project>"
subtitle: "<the subtitle of the project>"
```

```
documentclass: <the document class>
```

There are five document classes. i use mainly `article` if i want to create a short lab report which doesn't have chapters but sections that flow after each other from page to page. Here, i use `book` because it's a book that has chapters whereas each chapter begins on a new page.

```
papersize: <paper format>
```

This can be set for instance to `a4`.

```
geometry: top=<top>cm, right=<right>cm, bottom=<bottom>cm, left=<left>cm
```

`geometry` takes the values for margins from the given directions in centimeters.

```
classoption: <options for the document class separated by commas>
```

These are the options for the document class. i want my text to be mainly in one column, therefore `onecolumn` and printed on both sides - therefore `twoside`.

```
linestretch: <line height: how many lines>
```

```
fontsize: <size of the font in points>pt
mainfont: <font name>
```

```
bibliography: [book.bib]
```

This is the reference to the [bibliography file](#book_bib).


```
link-citations: yes
```

i want the references inside the text to be linked to the appropriate reference list items.

```
lof: yes
```

i want the list of figures to be displayed.

```
lot: yes
```

i want the list of tables to be displayed not the logo of the Polish airlines company that we can see on the background as Kim Wilde was delivering a concert in Sopot in 1988 [@kim].








For me, regarding cross-references, the following things are important:
It must be possible to cross-reference between files.
R code in one file must be accessible in another file.
Citations in table captions using kableStyling must be possible.

Currently, bookdown supports all of them if the output