# Setup of the project


After creating many projects using *bookdown*, i was ready to turn a project into a template. In order to turn a repository to a template, i went to GitHub, entered my project, chose *Settings* and checked *Template repository*. For a new project, i went to *New repository* and chose my template as *Repository template*. Another way to do the latter thing is to go to the main page of the template repository and click *Use this template*.

In RStudio Server, i created the new project: *File* -> *New Project…* -> *Version Control* -> *Git*, entered the HTTPS version of *Uniform Resource Locator* (URL) of my template repository for *Repository URL* and clicked *Create Project*.

RStudio Server doesn't rename the project metadata file *\*.Rproj* automatically. i did the rename manually and reopened the project: *File* -> *Open Project…*.

In order to push into the remote repository i need to create a key that can be used to unlock the lock to the repository in GitHub. i let to generate the key:

```{bash eval = FALSE}
ssh-keygen
```

This command first generates the following output:

> Generating public/private rsa key pair.  
> Enter file in which to save the key (/home/kalmer/.ssh/id_rsa):

As i have many projects in GitHub i need to have many keys as one key can't be used for many projects. Therefore, i also write a new file name for the key:

```
/home/kalmer/.ssh/<name-of-project>
```

The content of the newly created public key must be copied into GitHub for the named project as deploying the key by also allowing write access. i also have to inform my server about the connections of the newly created key by adding the following lines into *~/.ssh/config*:

```
Host github.com-<name-of-project>
 HostName github.com
 User git
 IdentityFile ~/.ssh/<name-of-project>
```

So far, *git* has no information on the newly cloned project about it's credentials. i need to tell it this information in order to be able to push my changes into the remote repository by changing the file *.git/config* inside my project's folder by setting a new value for *url*:

```
url = git@github.com-<name-of-project>:<username-in-github>/<name-of-project>.git
```

From now on, it's possible to edit the newly created project and push its changes into GitHub.

Once the project has some content i want it to share both as source code and human-friendly writing.

For making the writing viewable as a website, i need to create a subdomain for it, connect the subdomain to the project's output folder in *nginx*'s settings.

Inside RStudio Server, i want to make some changes right at the beginning before the first building as it's a new project. One of them is to change the name of the output file in *\_bookdown.yml*:

[]{#book-filename}
```
book_filename: "<name-of-project>" 
```

Samuti tasub koheselt muuta faili *README.md* sisu projektile vastavaks.

i need to update the repository Uniform Resource Locator (URL) in *\_output.yml* for `bookdown::bs4_book`:

```
repo: https://github.com/<username-in-github>/<name-of-project>
```
